// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Actor is the predicate function for actor builders.
type Actor func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Director is the predicate function for director builders.
type Director func(*sql.Selector)

// Favorite is the predicate function for favorite builders.
type Favorite func(*sql.Selector)

// Like is the predicate function for like builders.
type Like func(*sql.Selector)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
