// Code generated by ent, DO NOT EDIT.

package director

import (
	"imdbv2/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// ProfileImage applies equality check predicate on the "profileImage" field. It's identical to ProfileImageEQ.
func ProfileImage(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldProfileImage), v))
	})
}

// BornAt applies equality check predicate on the "bornAt" field. It's identical to BornAtEQ.
func BornAt(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBornAt), v))
	})
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescription), v))
	})
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Director {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Director {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// ProfileImageEQ applies the EQ predicate on the "profileImage" field.
func ProfileImageEQ(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldProfileImage), v))
	})
}

// ProfileImageNEQ applies the NEQ predicate on the "profileImage" field.
func ProfileImageNEQ(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldProfileImage), v))
	})
}

// ProfileImageIn applies the In predicate on the "profileImage" field.
func ProfileImageIn(vs ...string) predicate.Director {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldProfileImage), v...))
	})
}

// ProfileImageNotIn applies the NotIn predicate on the "profileImage" field.
func ProfileImageNotIn(vs ...string) predicate.Director {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldProfileImage), v...))
	})
}

// ProfileImageGT applies the GT predicate on the "profileImage" field.
func ProfileImageGT(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldProfileImage), v))
	})
}

// ProfileImageGTE applies the GTE predicate on the "profileImage" field.
func ProfileImageGTE(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldProfileImage), v))
	})
}

// ProfileImageLT applies the LT predicate on the "profileImage" field.
func ProfileImageLT(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldProfileImage), v))
	})
}

// ProfileImageLTE applies the LTE predicate on the "profileImage" field.
func ProfileImageLTE(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldProfileImage), v))
	})
}

// ProfileImageContains applies the Contains predicate on the "profileImage" field.
func ProfileImageContains(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldProfileImage), v))
	})
}

// ProfileImageHasPrefix applies the HasPrefix predicate on the "profileImage" field.
func ProfileImageHasPrefix(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldProfileImage), v))
	})
}

// ProfileImageHasSuffix applies the HasSuffix predicate on the "profileImage" field.
func ProfileImageHasSuffix(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldProfileImage), v))
	})
}

// ProfileImageEqualFold applies the EqualFold predicate on the "profileImage" field.
func ProfileImageEqualFold(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldProfileImage), v))
	})
}

// ProfileImageContainsFold applies the ContainsFold predicate on the "profileImage" field.
func ProfileImageContainsFold(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldProfileImage), v))
	})
}

// BornAtEQ applies the EQ predicate on the "bornAt" field.
func BornAtEQ(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBornAt), v))
	})
}

// BornAtNEQ applies the NEQ predicate on the "bornAt" field.
func BornAtNEQ(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldBornAt), v))
	})
}

// BornAtIn applies the In predicate on the "bornAt" field.
func BornAtIn(vs ...string) predicate.Director {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldBornAt), v...))
	})
}

// BornAtNotIn applies the NotIn predicate on the "bornAt" field.
func BornAtNotIn(vs ...string) predicate.Director {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldBornAt), v...))
	})
}

// BornAtGT applies the GT predicate on the "bornAt" field.
func BornAtGT(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldBornAt), v))
	})
}

// BornAtGTE applies the GTE predicate on the "bornAt" field.
func BornAtGTE(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldBornAt), v))
	})
}

// BornAtLT applies the LT predicate on the "bornAt" field.
func BornAtLT(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldBornAt), v))
	})
}

// BornAtLTE applies the LTE predicate on the "bornAt" field.
func BornAtLTE(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldBornAt), v))
	})
}

// BornAtContains applies the Contains predicate on the "bornAt" field.
func BornAtContains(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldBornAt), v))
	})
}

// BornAtHasPrefix applies the HasPrefix predicate on the "bornAt" field.
func BornAtHasPrefix(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldBornAt), v))
	})
}

// BornAtHasSuffix applies the HasSuffix predicate on the "bornAt" field.
func BornAtHasSuffix(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldBornAt), v))
	})
}

// BornAtEqualFold applies the EqualFold predicate on the "bornAt" field.
func BornAtEqualFold(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldBornAt), v))
	})
}

// BornAtContainsFold applies the ContainsFold predicate on the "bornAt" field.
func BornAtContainsFold(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldBornAt), v))
	})
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDescription), v))
	})
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDescription), v))
	})
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Director {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDescription), v...))
	})
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Director {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDescription), v...))
	})
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDescription), v))
	})
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDescription), v))
	})
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDescription), v))
	})
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDescription), v))
	})
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDescription), v))
	})
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDescription), v))
	})
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDescription), v))
	})
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDescription), v))
	})
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDescription), v))
	})
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUserID), v))
	})
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Director {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUserID), v...))
	})
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Director {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUserID), v...))
	})
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldUserID)))
	})
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldUserID)))
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMovies applies the HasEdge predicate on the "movies" edge.
func HasMovies() predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MoviesTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MoviesTable, MoviesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMoviesWith applies the HasEdge predicate on the "movies" edge with a given conditions (other predicates).
func HasMoviesWith(preds ...predicate.Movie) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MoviesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MoviesTable, MoviesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Director) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Director) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Director) predicate.Director {
	return predicate.Director(func(s *sql.Selector) {
		p(s.Not())
	})
}
