// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type DirectorInput struct {
	Name string `json:"name"`
}

type MovieInput struct {
	Description string `json:"description"`
	Title       string `json:"title"`
	Rank        int    `json:"rank"`
	DirectorID  int    `json:"director_id"`
}

type ReviewInput struct {
	Text string `json:"text"`
	Rank int    `json:"rank"`
}

type UserInput struct {
	Firstname   string `json:"firstname"`
	Lastname    string `json:"lastname"`
	Nickname    string `json:"nickname"`
	Description string `json:"description"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	Birthday    string `json:"birthday"`
}
