// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"imdbv2/ent/actor"
	"imdbv2/ent/movie"
	"imdbv2/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ActorUpdate is the builder for updating Actor entities.
type ActorUpdate struct {
	config
	hooks    []Hook
	mutation *ActorMutation
}

// Where appends a list predicates to the ActorUpdate builder.
func (au *ActorUpdate) Where(ps ...predicate.Actor) *ActorUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *ActorUpdate) SetName(s string) *ActorUpdate {
	au.mutation.SetName(s)
	return au
}

// SetCharacterName sets the "character_name" field.
func (au *ActorUpdate) SetCharacterName(s string) *ActorUpdate {
	au.mutation.SetCharacterName(s)
	return au
}

// SetImage sets the "image" field.
func (au *ActorUpdate) SetImage(s string) *ActorUpdate {
	au.mutation.SetImage(s)
	return au
}

// SetMovieID sets the "movie_id" field.
func (au *ActorUpdate) SetMovieID(i int) *ActorUpdate {
	au.mutation.ResetMovieID()
	au.mutation.SetMovieID(i)
	return au
}

// AddMovieID adds i to the "movie_id" field.
func (au *ActorUpdate) AddMovieID(i int) *ActorUpdate {
	au.mutation.AddMovieID(i)
	return au
}

// AddActorIDs adds the "actors" edge to the Movie entity by IDs.
func (au *ActorUpdate) AddActorIDs(ids ...int) *ActorUpdate {
	au.mutation.AddActorIDs(ids...)
	return au
}

// AddActors adds the "actors" edges to the Movie entity.
func (au *ActorUpdate) AddActors(m ...*Movie) *ActorUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return au.AddActorIDs(ids...)
}

// Mutation returns the ActorMutation object of the builder.
func (au *ActorUpdate) Mutation() *ActorMutation {
	return au.mutation
}

// ClearActors clears all "actors" edges to the Movie entity.
func (au *ActorUpdate) ClearActors() *ActorUpdate {
	au.mutation.ClearActors()
	return au
}

// RemoveActorIDs removes the "actors" edge to Movie entities by IDs.
func (au *ActorUpdate) RemoveActorIDs(ids ...int) *ActorUpdate {
	au.mutation.RemoveActorIDs(ids...)
	return au
}

// RemoveActors removes "actors" edges to Movie entities.
func (au *ActorUpdate) RemoveActors(m ...*Movie) *ActorUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return au.RemoveActorIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *ActorUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(au.hooks) == 0 {
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ActorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *ActorUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *ActorUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *ActorUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *ActorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   actor.Table,
			Columns: actor.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: actor.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: actor.FieldName,
		})
	}
	if value, ok := au.mutation.CharacterName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: actor.FieldCharacterName,
		})
	}
	if value, ok := au.mutation.Image(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: actor.FieldImage,
		})
	}
	if value, ok := au.mutation.MovieID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: actor.FieldMovieID,
		})
	}
	if value, ok := au.mutation.AddedMovieID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: actor.FieldMovieID,
		})
	}
	if au.mutation.ActorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   actor.ActorsTable,
			Columns: actor.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedActorsIDs(); len(nodes) > 0 && !au.mutation.ActorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   actor.ActorsTable,
			Columns: actor.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ActorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   actor.ActorsTable,
			Columns: actor.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ActorUpdateOne is the builder for updating a single Actor entity.
type ActorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActorMutation
}

// SetName sets the "name" field.
func (auo *ActorUpdateOne) SetName(s string) *ActorUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetCharacterName sets the "character_name" field.
func (auo *ActorUpdateOne) SetCharacterName(s string) *ActorUpdateOne {
	auo.mutation.SetCharacterName(s)
	return auo
}

// SetImage sets the "image" field.
func (auo *ActorUpdateOne) SetImage(s string) *ActorUpdateOne {
	auo.mutation.SetImage(s)
	return auo
}

// SetMovieID sets the "movie_id" field.
func (auo *ActorUpdateOne) SetMovieID(i int) *ActorUpdateOne {
	auo.mutation.ResetMovieID()
	auo.mutation.SetMovieID(i)
	return auo
}

// AddMovieID adds i to the "movie_id" field.
func (auo *ActorUpdateOne) AddMovieID(i int) *ActorUpdateOne {
	auo.mutation.AddMovieID(i)
	return auo
}

// AddActorIDs adds the "actors" edge to the Movie entity by IDs.
func (auo *ActorUpdateOne) AddActorIDs(ids ...int) *ActorUpdateOne {
	auo.mutation.AddActorIDs(ids...)
	return auo
}

// AddActors adds the "actors" edges to the Movie entity.
func (auo *ActorUpdateOne) AddActors(m ...*Movie) *ActorUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return auo.AddActorIDs(ids...)
}

// Mutation returns the ActorMutation object of the builder.
func (auo *ActorUpdateOne) Mutation() *ActorMutation {
	return auo.mutation
}

// ClearActors clears all "actors" edges to the Movie entity.
func (auo *ActorUpdateOne) ClearActors() *ActorUpdateOne {
	auo.mutation.ClearActors()
	return auo
}

// RemoveActorIDs removes the "actors" edge to Movie entities by IDs.
func (auo *ActorUpdateOne) RemoveActorIDs(ids ...int) *ActorUpdateOne {
	auo.mutation.RemoveActorIDs(ids...)
	return auo
}

// RemoveActors removes "actors" edges to Movie entities.
func (auo *ActorUpdateOne) RemoveActors(m ...*Movie) *ActorUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return auo.RemoveActorIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *ActorUpdateOne) Select(field string, fields ...string) *ActorUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Actor entity.
func (auo *ActorUpdateOne) Save(ctx context.Context) (*Actor, error) {
	var (
		err  error
		node *Actor
	)
	if len(auo.hooks) == 0 {
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ActorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *ActorUpdateOne) SaveX(ctx context.Context) *Actor {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *ActorUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *ActorUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *ActorUpdateOne) sqlSave(ctx context.Context) (_node *Actor, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   actor.Table,
			Columns: actor.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: actor.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Actor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, actor.FieldID)
		for _, f := range fields {
			if !actor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != actor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: actor.FieldName,
		})
	}
	if value, ok := auo.mutation.CharacterName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: actor.FieldCharacterName,
		})
	}
	if value, ok := auo.mutation.Image(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: actor.FieldImage,
		})
	}
	if value, ok := auo.mutation.MovieID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: actor.FieldMovieID,
		})
	}
	if value, ok := auo.mutation.AddedMovieID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: actor.FieldMovieID,
		})
	}
	if auo.mutation.ActorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   actor.ActorsTable,
			Columns: actor.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedActorsIDs(); len(nodes) > 0 && !auo.mutation.ActorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   actor.ActorsTable,
			Columns: actor.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ActorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   actor.ActorsTable,
			Columns: actor.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Actor{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
