// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"imdbv2/ent/director"
	"imdbv2/ent/movie"
	"imdbv2/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DirectorCreate is the builder for creating a Director entity.
type DirectorCreate struct {
	config
	mutation *DirectorMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (dc *DirectorCreate) SetName(s string) *DirectorCreate {
	dc.mutation.SetName(s)
	return dc
}

// SetProfileImage sets the "profileImage" field.
func (dc *DirectorCreate) SetProfileImage(s string) *DirectorCreate {
	dc.mutation.SetProfileImage(s)
	return dc
}

// SetBornAt sets the "bornAt" field.
func (dc *DirectorCreate) SetBornAt(s string) *DirectorCreate {
	dc.mutation.SetBornAt(s)
	return dc
}

// SetNillableBornAt sets the "bornAt" field if the given value is not nil.
func (dc *DirectorCreate) SetNillableBornAt(s *string) *DirectorCreate {
	if s != nil {
		dc.SetBornAt(*s)
	}
	return dc
}

// SetDescription sets the "description" field.
func (dc *DirectorCreate) SetDescription(s string) *DirectorCreate {
	dc.mutation.SetDescription(s)
	return dc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (dc *DirectorCreate) SetNillableDescription(s *string) *DirectorCreate {
	if s != nil {
		dc.SetDescription(*s)
	}
	return dc
}

// SetUserID sets the "user_id" field.
func (dc *DirectorCreate) SetUserID(i int) *DirectorCreate {
	dc.mutation.SetUserID(i)
	return dc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (dc *DirectorCreate) SetNillableUserID(i *int) *DirectorCreate {
	if i != nil {
		dc.SetUserID(*i)
	}
	return dc
}

// SetUser sets the "user" edge to the User entity.
func (dc *DirectorCreate) SetUser(u *User) *DirectorCreate {
	return dc.SetUserID(u.ID)
}

// AddMovieIDs adds the "movies" edge to the Movie entity by IDs.
func (dc *DirectorCreate) AddMovieIDs(ids ...int) *DirectorCreate {
	dc.mutation.AddMovieIDs(ids...)
	return dc
}

// AddMovies adds the "movies" edges to the Movie entity.
func (dc *DirectorCreate) AddMovies(m ...*Movie) *DirectorCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return dc.AddMovieIDs(ids...)
}

// Mutation returns the DirectorMutation object of the builder.
func (dc *DirectorCreate) Mutation() *DirectorMutation {
	return dc.mutation
}

// Save creates the Director in the database.
func (dc *DirectorCreate) Save(ctx context.Context) (*Director, error) {
	var (
		err  error
		node *Director
	)
	dc.defaults()
	if len(dc.hooks) == 0 {
		if err = dc.check(); err != nil {
			return nil, err
		}
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DirectorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = dc.check(); err != nil {
				return nil, err
			}
			dc.mutation = mutation
			if node, err = dc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			if dc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, dc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Director)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from DirectorMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DirectorCreate) SaveX(ctx context.Context) *Director {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DirectorCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DirectorCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dc *DirectorCreate) defaults() {
	if _, ok := dc.mutation.BornAt(); !ok {
		v := director.DefaultBornAt
		dc.mutation.SetBornAt(v)
	}
	if _, ok := dc.mutation.Description(); !ok {
		v := director.DefaultDescription
		dc.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DirectorCreate) check() error {
	if _, ok := dc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Director.name"`)}
	}
	if _, ok := dc.mutation.ProfileImage(); !ok {
		return &ValidationError{Name: "profileImage", err: errors.New(`ent: missing required field "Director.profileImage"`)}
	}
	if _, ok := dc.mutation.BornAt(); !ok {
		return &ValidationError{Name: "bornAt", err: errors.New(`ent: missing required field "Director.bornAt"`)}
	}
	if _, ok := dc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Director.description"`)}
	}
	return nil
}

func (dc *DirectorCreate) sqlSave(ctx context.Context) (*Director, error) {
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (dc *DirectorCreate) createSpec() (*Director, *sqlgraph.CreateSpec) {
	var (
		_node = &Director{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: director.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: director.FieldID,
			},
		}
	)
	if value, ok := dc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldName,
		})
		_node.Name = value
	}
	if value, ok := dc.mutation.ProfileImage(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldProfileImage,
		})
		_node.ProfileImage = value
	}
	if value, ok := dc.mutation.BornAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldBornAt,
		})
		_node.BornAt = value
	}
	if value, ok := dc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldDescription,
		})
		_node.Description = value
	}
	if nodes := dc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   director.UserTable,
			Columns: []string{director.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.mutation.MoviesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.MoviesTable,
			Columns: []string{director.MoviesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DirectorCreateBulk is the builder for creating many Director entities in bulk.
type DirectorCreateBulk struct {
	config
	builders []*DirectorCreate
}

// Save creates the Director entities in the database.
func (dcb *DirectorCreateBulk) Save(ctx context.Context) ([]*Director, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Director, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DirectorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DirectorCreateBulk) SaveX(ctx context.Context) []*Director {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DirectorCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DirectorCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}
