// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"imdbv2/ent/director"
	"imdbv2/ent/movie"
	"imdbv2/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DirectorUpdate is the builder for updating Director entities.
type DirectorUpdate struct {
	config
	hooks    []Hook
	mutation *DirectorMutation
}

// Where appends a list predicates to the DirectorUpdate builder.
func (du *DirectorUpdate) Where(ps ...predicate.Director) *DirectorUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetName sets the "name" field.
func (du *DirectorUpdate) SetName(s string) *DirectorUpdate {
	du.mutation.SetName(s)
	return du
}

// SetProfileImage sets the "profileImage" field.
func (du *DirectorUpdate) SetProfileImage(s string) *DirectorUpdate {
	du.mutation.SetProfileImage(s)
	return du
}

// SetBornAt sets the "bornAt" field.
func (du *DirectorUpdate) SetBornAt(s string) *DirectorUpdate {
	du.mutation.SetBornAt(s)
	return du
}

// SetDescription sets the "description" field.
func (du *DirectorUpdate) SetDescription(s string) *DirectorUpdate {
	du.mutation.SetDescription(s)
	return du
}

// AddMovieIDs adds the "movies" edge to the Movie entity by IDs.
func (du *DirectorUpdate) AddMovieIDs(ids ...int) *DirectorUpdate {
	du.mutation.AddMovieIDs(ids...)
	return du
}

// AddMovies adds the "movies" edges to the Movie entity.
func (du *DirectorUpdate) AddMovies(m ...*Movie) *DirectorUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return du.AddMovieIDs(ids...)
}

// Mutation returns the DirectorMutation object of the builder.
func (du *DirectorUpdate) Mutation() *DirectorMutation {
	return du.mutation
}

// ClearMovies clears all "movies" edges to the Movie entity.
func (du *DirectorUpdate) ClearMovies() *DirectorUpdate {
	du.mutation.ClearMovies()
	return du
}

// RemoveMovieIDs removes the "movies" edge to Movie entities by IDs.
func (du *DirectorUpdate) RemoveMovieIDs(ids ...int) *DirectorUpdate {
	du.mutation.RemoveMovieIDs(ids...)
	return du
}

// RemoveMovies removes "movies" edges to Movie entities.
func (du *DirectorUpdate) RemoveMovies(m ...*Movie) *DirectorUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return du.RemoveMovieIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DirectorUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(du.hooks) == 0 {
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DirectorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			if du.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DirectorUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DirectorUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DirectorUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DirectorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   director.Table,
			Columns: director.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: director.FieldID,
			},
		},
	}
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldName,
		})
	}
	if value, ok := du.mutation.ProfileImage(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldProfileImage,
		})
	}
	if value, ok := du.mutation.BornAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldBornAt,
		})
	}
	if value, ok := du.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldDescription,
		})
	}
	if du.mutation.MoviesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.MoviesTable,
			Columns: []string{director.MoviesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.RemovedMoviesIDs(); len(nodes) > 0 && !du.mutation.MoviesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.MoviesTable,
			Columns: []string{director.MoviesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.MoviesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.MoviesTable,
			Columns: []string{director.MoviesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{director.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// DirectorUpdateOne is the builder for updating a single Director entity.
type DirectorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DirectorMutation
}

// SetName sets the "name" field.
func (duo *DirectorUpdateOne) SetName(s string) *DirectorUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetProfileImage sets the "profileImage" field.
func (duo *DirectorUpdateOne) SetProfileImage(s string) *DirectorUpdateOne {
	duo.mutation.SetProfileImage(s)
	return duo
}

// SetBornAt sets the "bornAt" field.
func (duo *DirectorUpdateOne) SetBornAt(s string) *DirectorUpdateOne {
	duo.mutation.SetBornAt(s)
	return duo
}

// SetDescription sets the "description" field.
func (duo *DirectorUpdateOne) SetDescription(s string) *DirectorUpdateOne {
	duo.mutation.SetDescription(s)
	return duo
}

// AddMovieIDs adds the "movies" edge to the Movie entity by IDs.
func (duo *DirectorUpdateOne) AddMovieIDs(ids ...int) *DirectorUpdateOne {
	duo.mutation.AddMovieIDs(ids...)
	return duo
}

// AddMovies adds the "movies" edges to the Movie entity.
func (duo *DirectorUpdateOne) AddMovies(m ...*Movie) *DirectorUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return duo.AddMovieIDs(ids...)
}

// Mutation returns the DirectorMutation object of the builder.
func (duo *DirectorUpdateOne) Mutation() *DirectorMutation {
	return duo.mutation
}

// ClearMovies clears all "movies" edges to the Movie entity.
func (duo *DirectorUpdateOne) ClearMovies() *DirectorUpdateOne {
	duo.mutation.ClearMovies()
	return duo
}

// RemoveMovieIDs removes the "movies" edge to Movie entities by IDs.
func (duo *DirectorUpdateOne) RemoveMovieIDs(ids ...int) *DirectorUpdateOne {
	duo.mutation.RemoveMovieIDs(ids...)
	return duo
}

// RemoveMovies removes "movies" edges to Movie entities.
func (duo *DirectorUpdateOne) RemoveMovies(m ...*Movie) *DirectorUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return duo.RemoveMovieIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DirectorUpdateOne) Select(field string, fields ...string) *DirectorUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Director entity.
func (duo *DirectorUpdateOne) Save(ctx context.Context) (*Director, error) {
	var (
		err  error
		node *Director
	)
	if len(duo.hooks) == 0 {
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DirectorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			if duo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = duo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, duo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DirectorUpdateOne) SaveX(ctx context.Context) *Director {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DirectorUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DirectorUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DirectorUpdateOne) sqlSave(ctx context.Context) (_node *Director, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   director.Table,
			Columns: director.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: director.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Director.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, director.FieldID)
		for _, f := range fields {
			if !director.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != director.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldName,
		})
	}
	if value, ok := duo.mutation.ProfileImage(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldProfileImage,
		})
	}
	if value, ok := duo.mutation.BornAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldBornAt,
		})
	}
	if value, ok := duo.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: director.FieldDescription,
		})
	}
	if duo.mutation.MoviesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.MoviesTable,
			Columns: []string{director.MoviesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.RemovedMoviesIDs(); len(nodes) > 0 && !duo.mutation.MoviesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.MoviesTable,
			Columns: []string{director.MoviesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.MoviesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   director.MoviesTable,
			Columns: []string{director.MoviesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: movie.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Director{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{director.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
