// Code generated by entc, DO NOT EDIT.

package actorsmovies

const (
	// Label holds the string label denoting the actorsmovies type in the database.
	Label = "actors_movies"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMovieTitle holds the string denoting the movie_title field in the database.
	FieldMovieTitle = "movie_title"
	// FieldMovieID holds the string denoting the movie_id field in the database.
	FieldMovieID = "movie_id"
	// FieldActorName holds the string denoting the actor_name field in the database.
	FieldActorName = "actor_name"
	// FieldActorID holds the string denoting the actor_id field in the database.
	FieldActorID = "actor_id"
	// Table holds the table name of the actorsmovies in the database.
	Table = "actors_movies"
)

// Columns holds all SQL columns for actorsmovies fields.
var Columns = []string{
	FieldID,
	FieldMovieTitle,
	FieldMovieID,
	FieldActorName,
	FieldActorID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
